---
- hosts: worker
  vars_files:
  - env_variables

  tasks:
  - name: Copying token to worker nodes
    copy: src={{ token_file }} dest=join_token.sh mode=0755

  - name: Joining worker nodes with kubernetes master
    command: sh join_token.sh
